apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80        # The port that will be exposed on the service
      targetPort: 80  # The port that the pods are listening on
      nodePort: 30080  # Optional: You can specify a port or let Kubernetes assign one
  type: NodePort
