apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: pm55/infra-frontend:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "200m"       # Minimum CPU requested per pod
            memory: "256Mi"   # Minimum memory requested per pod
          limits:
            cpu: "500m"       # Maximum CPU usage per pod
            memory: "512Mi"   # Maximum memory usage per pod
