apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: pm55/infra-backend:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          value: mongodb://mongo-service:27017/ordersdb
        - name: RABBITMQ_URL
          value: amqp://rabbitmq-service:5672
        resources:
          requests:
            cpu: "200m"       # Minimum CPU requested per pod
            memory: "512Mi"   # Minimum memory requested per pod
          limits:
            cpu: "500m"       # Maximum CPU usage per pod
            memory: "1024Mi"  # Maximum memory usage per pod
